title:        Millón de Monos
tagline:      'Weblog de Manuel Aristarán'
description:  'Weblog de Manuel Aristarán'
url:          https://blog.jazzido.com
version:      1.1.1
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
paginate:     5
google_analytics: UA-68057-6
disqus: millondemonos
locale: es_AR
gems: [jekyll-paginate, jekyll-archives, jekyll-seo-tag]
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
jekyll-archives:
  enabled: [year]
  layout: archive
  permalinks:
    year: '/:year/'
